apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "kimai2.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kimai2.selectorLabels" . | nindent 6 }}

  {{- if .Values.updateStrategy }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kimai2.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ADMINMAIL
              value: {{ .Values.kimaiAdminEmail }}
            - name: APP_ENV
              value: {{ .Values.kimaiEnvironment }}
            - name: TRUSTED_HOSTS
              value: localhost,{{ .Values.ingress.hostname }}
            - name: MAILER_FROM
              value: {{ .Values.kimaiMailerFrom }}
          envFrom:
            - secretRef:
                name: {{ include "kimai2.name" . }}-secret
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /en/login
              port: http
              httpHeaders:
              - name: Host
                value: localhost
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /en/login
              port: http
              httpHeaders:
                - name: Host
                  value: localhost
            periodSeconds: 10
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /opt/kimai/var
              name: kimai-data
            {{- if .Values.configuration }}
            - name: config
              mountPath: /opt/kimai/config/packages/local.yaml
              subPath: local.yaml
            {{- end }}
            {{- if not empty .Values.exports }}
            {{- range $key, $val := .Values.exports }}
            - mountPath: /opt/kimai/var/export/{{ $key }}
              name: exports
              subPath: {{ $key }}
            {{- end }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: kimai-data
          {{- if  .Values.persistence.enabled}}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "common.names.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if .Values.configuration }}
        - name: config
          configMap:
            name: {{ include "kimai2.name" . }}-config
        {{- end }}
        {{- if not empty .Values.exports }}
        - name: exports
          configMap:
            name: {{ include "kimai2.name" . }}-exports
        {{- end }}
